version: '3.1'

services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: reddit
    volumes:
      - .\Dockerdata\db:/var/lib/postgresql/data
  db-test:
    image: postgres
    environment: 
      POSTGRES_DB: reddit-test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5431:5432
